trigger:
  branches:
    include:
      - main  # Change this if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: mirror-git-repository-vsts-task@1
  inputs:
    sourceGitRepositoryUri: '$(Build.Repository.Uri)'
    sourceVerifySSLCertificate: false
    destinationGitRepositoryUri: 'https://github.com/xuanphongit/First-Clone/'
    destinationGitRepositoryPersonalAccessToken: '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'
