trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Ensures the full repo is checked out

  - script: |
      sudo apt update && sudo apt install gh jq -y
    displayName: 'Install GitHub CLI & jq'

  - script: |
      git clone --mirror "https://thienthutula1109.visualstudio.com/phongmx/_git/First%20Repo" repo_mirror
      cd repo_mirror

      # Set GitHub as the new remote repository
      git remote set-url origin "https://$(GITHUB_PAT)@github.com/xuanphongit/First-Clone.git"

      # Push all branches, tags, and history to GitHub
      git push --mirror --force
    displayName: 'Mirror Azure DevOps Repo to GitHub'
    env:
      GITHUB_PAT: $(GITHUB_PAT)

schedules:
  - cron: "0 0 * * *"  # Runs daily at midnight UTC
    displayName: "Daily Sync to GitHub"
    branches:
      include:
        - main
