trigger:
  - '*' #trigger mỗi khi có thay đổi trên bất kì nhánh nào.

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: GithubPush@4
  displayName: 'Mirror to GitHub'
  inputs:
    targetRepo: 'xuanphongit/First-Clone'
    branch: '$(Build.SourceBranchName)'
    serviceConnection: 'xuanphongit'
    forcePush: true
    tagSource: 'off'