trigger:
  - '*' #trigger mỗi khi có thay đổi trên bất kì nhánh nào.

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: Bash@3
  displayName: 'Mirror to GitHub'
  inputs:
    targetType: 'inline'
    script: |
      git remote add github "https://$(githubPAT)@github.com/xuanphongit/First-Clone.git"
      git push --mirror github
  env:
    githubPAT: $(GITHUB_PAT)

variables:
  - group: GitHubCredentials
  - name: GITHUB_PAT
    value: $[variables['GitHubPAT']]