trigger:
  branches:
    include:
      - main  # Change if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |     
      git clone --mirror "https://thienthutula1109.visualstudio.com/phongmx/_git/First%20Repo"
      cd First%20Repo.git

      git remote set-url origin "https://$(GITHUB_PAT)@github.com/xuanphongit/First-Clone.git"
      git push --mirror --force
    displayName: 'Mirror Azure DevOps Repo to GitHub'
    env:
      GITHUB_PAT: $(GITHUB_PAT)  # Securely use the stored token
