trigger:
  - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true

- task: Bash@3
  displayName: 'Mirror to GitHub'
  inputs:
    targetType: 'inline'
    script: |
      git remote add github "https://$(githubPAT)@github.com/xuanphongit/First-Clone.git"
      git push --mirror github
  env:
    GITHUB_PAT: $(GITHUB_PAT)

variables:
  - name: GITHUB_PAT
    value: $(endpoint.SYSTEMVSSCONNECTIONPASSWORD_xuanphongit)